name: packer

on:
  push:

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
#       - name: Set up Go
#         uses: actions/setup-go@v1
#       - name: print golang
#         run: powershell go --version
      - name: download wix msi tools
        run: |
          powershell Invoke-WebRequest https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix311.zip 
          powershell Expand-Archive wix311.zip -DestinationPath wix311
      - name: packaging windows msi
        run: |
          powershell ./wix311/candle.exe -out simple.wixobj simple.wxs
          powershell ./wix311/light.exe -b . -ext WixUIExtension simple.wixobj -out simple.msi
      - name: list
        run: powershell ls
      - name: "publish action-artifact zip"
        uses: actions/upload-artifact@v1
        with:
          name: msi
          path: ./simple.msi
  release:
    needs: [pack]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download artefacts msi installer
        uses: actions/download-artifact@v1
        with:
          name: msi
      - name: zip
        run: |
         zip installer msi/simple.msi
         
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./installer.zip
          asset_name: installer.zip
          asset_content_type: application/zip
