name: packer

on:
  push:

jobs:
  build-package-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: sign
        run: tools/signtool.exe sign //v //s MY //n "gcn" //fd sha256 //tr http://timestamp.comodoca.com/?td=sha256 //td sha256 simple.exe
        shell: bash
#       - name: Set up Go
#         uses: actions/setup-go@v1
#         with:
#           go-version: 1.14.1
#       - name: print golang
#         run: go --version
#       - name: install asti
#         run: |
#           export GOPATH=$HOME/go
#           export GOBIN=$HOME/go/bin
#           export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
#           go get -u github.com/asticode/go-astilectron-bundler/...
#           go get -u github.com/asticode/go-astilectron-bootstrap
#           go install github.com/asticode/go-astilectron-bundler/astilectron-bundler
#         shell: bash
      

      # - name: download wix msi tools
      #   run: |
      #     powershell Invoke-WebRequest https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix311.zip 
      #     powershell Expand-Archive wix311.zip -DestinationPath wix311
      # - name: packaging windows msi
      #   run: |
      #     powershell ./wix311/candle.exe -out simple.wixobj simple.wxs
      #     powershell ./wix311/light.exe -b . -ext WixUIExtension simple.wixobj -out simple.msi
      
