name: packer

on:
  push:

jobs:
  build-package-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v1
      - name: print golang
        run: powershell go --version
      - name: download wix msi tools
        run: |
          powershell Invoke-WebRequest https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix311.zip 
          powershell Expand-Archive wix311.zip -DestinationPath wix311
      - name: packaging windows msi
        run: |
          powershell ./wix311/candle.exe -out simple.wixobj simple.wxs
          powershell ./wix311/light.exe -b . -ext WixUIExtension simple.wixobj -out simple.msi
      
